<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- Layer Dependencies -->
    <ProjectReference Include="..\ASPER.CORPORATE_BANKING.Application\ASPER.CORPORATE_BANKING.Application.csproj" />
    <ProjectReference Include="..\ASPER.CORPORATE_BANKING.Contract\ASPER.CORPORATE_BANKING.Contract.csproj" />
    <ProjectReference Include="..\ASPER.CORPORATE_BANKING.Domain\ASPER.CORPORATE_BANKING.Domain.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ASPER.Config.Grpc.Client" Version="1.2.7" />
    <PackageReference Include="ASPER.GLProcess.Grpc.Client" Version="2.0.2" />
    <PackageReference Include="ASPER.Notification.Contracts" Version="1.1.2" />
    <PackageReference Include="ClosedXML" Version="0.104.2" />
    <PackageReference Include="Dapper" Version="2.1.66" />

    <PackageReference Include="MassTransit" Version="8.2.5" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.2.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.0" />

    <!-- 👇 ADD THESE TWO FOR THE FACTORY FIX -->
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="8.0.0" />
  </ItemGroup>

</Project>
