syntax = "proto3";

option csharp_namespace = "ASPER.AuthService.Grpc";

package authservice;

service AuthService {
  rpc GetUserInfoByUserName (GetUserInfoRequest) returns (UserInfoResponse);
  rpc GetCustomerByUserId (GetCustomerRequest) returns (CustomerResponse);
}

message GetUserInfoRequest {
  string user_name = 1;
}

message GetCustomerRequest {
  string user_id = 1;
}

message UserInfoResponse {
  string user_id = 1;
  string user_name = 2;
  string email = 3;
  string full_name = 4;
  string phone_number = 5;
  bool is_active = 6;
  string role = 7;
  bool success = 8;
  string message = 9;
}

message CustomerResponse {
  string customer_id = 1;
  string customer_code = 2;
  string customer_name = 3;
  string user_id = 4;
  string email = 5;
  string mobile_no = 6;
  string nid_no = 7;
  bool success = 8;
  string message = 9;
}
