// <auto-generated />
using System;
using ASPER.CORPORATE_BANKING.Infrastructure.Data.NPGDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ASPER.CORPORATE_BANKING.Infrastructure.Migrations.PostgreSQL
{
    [DbContext(typeof(PostgreDbContext))]
    [Migration("20260912165502_initialData")]
    partial class initialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ASPER.CORPORATE_BANKING.Domain.Entities.ApprovalMatrixConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("approvedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("approvedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("effectiveFrom")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("effectiveTo")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("isApproved")
                        .HasColumnType("integer");

                    b.Property<int?>("isDelete")
                        .HasColumnType("integer")
                        .HasColumnName("IS_DELETE");

                    b.Property<int?>("transactionTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("UPDATED_AT");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("UPDATED_BY");

                    b.Property<int?>("version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("transactionTypeId");

                    b.ToTable("ApprovalMatrixConfig");
                });

            modelBuilder.Entity("ASPER.CORPORATE_BANKING.Domain.Entities.ApprovalMatrixSlab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("approvalMatrixConfigId")
                        .HasColumnType("integer");

                    b.Property<int?>("checkerRoleId")
                        .HasColumnType("integer");

                    b.Property<string>("checkerRoleName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("CREATED_BY");

                    b.Property<bool?>("isActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("isAutoApprove")
                        .HasColumnType("boolean");

                    b.Property<bool?>("isCheckerRequired")
                        .HasColumnType("boolean");

                    b.Property<int?>("isDelete")
                        .HasColumnType("integer")
                        .HasColumnName("IS_DELETE");

                    b.Property<decimal?>("maxAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("minAmount")
                        .HasColumnType("numeric");

                    b.Property<int?>("slabOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("UPDATED_AT");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("UPDATED_BY");

                    b.HasKey("Id");

                    b.HasIndex("approvalMatrixConfigId");

                    b.ToTable("ApprovalMatrixSlab");
                });

            modelBuilder.Entity("ASPER.CORPORATE_BANKING.Domain.Entities.ApprovalStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("approvalLogic")
                        .HasColumnType("text");

                    b.Property<int?>("approvalMatrixSlabId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("CREATED_BY");

                    b.Property<int?>("isDelete")
                        .HasColumnType("integer")
                        .HasColumnName("IS_DELETE");

                    b.Property<int?>("stepOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("UPDATED_AT");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("UPDATED_BY");

                    b.HasKey("Id");

                    b.HasIndex("approvalMatrixSlabId");

                    b.ToTable("ApprovalStep");
                });

            modelBuilder.Entity("ASPER.CORPORATE_BANKING.Domain.Entities.ApprovalStepRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("approvalStepId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("CREATED_BY");

                    b.Property<int?>("isDelete")
                        .HasColumnType("integer")
                        .HasColumnName("IS_DELETE");

                    b.Property<int?>("roleId")
                        .HasColumnType("integer");

                    b.Property<string>("roleName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("UPDATED_AT");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("UPDATED_BY");

                    b.HasKey("Id");

                    b.HasIndex("approvalStepId");

                    b.ToTable("ApprovalStepRole");
                });

            modelBuilder.Entity("ASPER.CORPORATE_BANKING.Domain.Entities.FileFieldMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("columnOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("dataType")
                        .HasColumnType("text");

                    b.Property<string>("excelColumnName")
                        .HasColumnType("text");

                    b.Property<string>("fieldKey")
                        .HasColumnType("text");

                    b.Property<int?>("fileTemplateConfigId")
                        .HasColumnType("integer");

                    b.Property<int?>("isDelete")
                        .HasColumnType("integer")
                        .HasColumnName("IS_DELETE");

                    b.Property<bool?>("isMandatory")
                        .HasColumnType("boolean");

                    b.Property<int?>("maxLength")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("UPDATED_AT");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("UPDATED_BY");

                    b.Property<string>("validationRegex")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("fileTemplateConfigId");

                    b.ToTable("FileFieldMapping");
                });

            modelBuilder.Entity("ASPER.CORPORATE_BANKING.Domain.Entities.FileTemplateConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("effectiveFrom")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("effectiveTo")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("isDelete")
                        .HasColumnType("integer")
                        .HasColumnName("IS_DELETE");

                    b.Property<int?>("transactionTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("UPDATED_AT");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("UPDATED_BY");

                    b.Property<int?>("version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("transactionTypeId");

                    b.ToTable("FileTemplateConfig");
                });

            modelBuilder.Entity("ASPER.CORPORATE_BANKING.Domain.Entities.TransactionApprovalAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("actionAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("actionByRoleId")
                        .HasColumnType("integer");

                    b.Property<string>("actionByRoleName")
                        .HasColumnType("text");

                    b.Property<int?>("actionByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("actionByUserName")
                        .HasColumnType("text");

                    b.Property<string>("actionType")
                        .HasColumnType("text");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("ipAddress")
                        .HasColumnType("text");

                    b.Property<int?>("isDelete")
                        .HasColumnType("integer")
                        .HasColumnName("IS_DELETE");

                    b.Property<string>("remarks")
                        .HasColumnType("text");

                    b.Property<int?>("stepOrder")
                        .HasColumnType("integer");

                    b.Property<int?>("transactionRecordId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("UPDATED_AT");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("UPDATED_BY");

                    b.HasKey("Id");

                    b.HasIndex("transactionRecordId");

                    b.ToTable("TransactionApprovalAction");
                });

            modelBuilder.Entity("ASPER.CORPORATE_BANKING.Domain.Entities.TransactionBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("approvalMatrixConfigId")
                        .HasColumnType("integer");

                    b.Property<Guid>("batchNo")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("fileName")
                        .HasColumnType("text");

                    b.Property<string>("fileStoragePath")
                        .HasColumnType("text");

                    b.Property<int?>("invalidRecords")
                        .HasColumnType("integer");

                    b.Property<int?>("isDelete")
                        .HasColumnType("integer")
                        .HasColumnName("IS_DELETE");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.Property<decimal?>("totalAmount")
                        .HasColumnType("numeric");

                    b.Property<int?>("totalRecords")
                        .HasColumnType("integer");

                    b.Property<int?>("transactionTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("UPDATED_AT");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("UPDATED_BY");

                    b.Property<DateTime?>("uploadedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("uploadedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("uploadedByUserName")
                        .HasColumnType("text");

                    b.Property<int?>("validRecords")
                        .HasColumnType("integer");

                    b.Property<string>("validationErrors")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("approvalMatrixConfigId");

                    b.HasIndex("transactionTypeId");

                    b.ToTable("TransactionBatch");
                });

            modelBuilder.Entity("ASPER.CORPORATE_BANKING.Domain.Entities.TransactionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("accountHolderName")
                        .HasColumnType("text");

                    b.Property<decimal?>("amount")
                        .HasColumnType("numeric");

                    b.Property<string>("bankAccountNo")
                        .HasColumnType("text");

                    b.Property<string>("beneficiaryAccountType")
                        .HasColumnType("text");

                    b.Property<string>("beneficiaryBankName")
                        .HasColumnType("text");

                    b.Property<string>("beneficiaryBranchName")
                        .HasColumnType("text");

                    b.Property<bool?>("checkerRequiredSnapshot")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("currency")
                        .HasColumnType("text");

                    b.Property<int?>("currentStepOrder")
                        .HasColumnType("integer");

                    b.Property<string>("externalSystemRefNo")
                        .HasColumnType("text");

                    b.Property<string>("failureReason")
                        .HasColumnType("text");

                    b.Property<string>("instructionRefNo")
                        .HasColumnType("text");

                    b.Property<int?>("isDelete")
                        .HasColumnType("integer")
                        .HasColumnName("IS_DELETE");

                    b.Property<int?>("matrixSlabId")
                        .HasColumnType("integer");

                    b.Property<string>("narration")
                        .HasColumnType("text");

                    b.Property<string>("priority")
                        .HasColumnType("text");

                    b.Property<string>("purposeCode")
                        .HasColumnType("text");

                    b.Property<string>("routingNumber")
                        .HasColumnType("text");

                    b.Property<int?>("rowNo")
                        .HasColumnType("integer");

                    b.Property<byte[]>("rowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("senderAccountName")
                        .HasColumnType("text");

                    b.Property<string>("senderAccountNo")
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.Property<int?>("transactionBatchId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("UPDATED_AT");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("UPDATED_BY");

                    b.Property<DateTime?>("valueDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("instructionRefNo")
                        .IsUnique();

                    b.HasIndex("matrixSlabId");

                    b.HasIndex("transactionBatchId");

                    b.ToTable("TransactionRecord");
                });

            modelBuilder.Entity("ASPER.CORPORATE_BANKING.Domain.Entities.TransactionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("code")
                        .HasColumnType("text");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<bool?>("isActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("isDelete")
                        .HasColumnType("integer")
                        .HasColumnName("IS_DELETE");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("UPDATED_AT");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("UPDATED_BY");

                    b.HasKey("Id");

                    b.ToTable("TransactionType");
                });

            modelBuilder.Entity("ASPER.CORPORATE_BANKING.Infrastructure.Audit.Outbox.AuditOutboxMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditOutboxMessage");
                });

            modelBuilder.Entity("ASPER.CORPORATE_BANKING.Domain.Entities.ApprovalMatrixConfig", b =>
                {
                    b.HasOne("ASPER.CORPORATE_BANKING.Domain.Entities.TransactionType", "transactionType")
                        .WithMany()
                        .HasForeignKey("transactionTypeId");

                    b.Navigation("transactionType");
                });

            modelBuilder.Entity("ASPER.CORPORATE_BANKING.Domain.Entities.ApprovalMatrixSlab", b =>
                {
                    b.HasOne("ASPER.CORPORATE_BANKING.Domain.Entities.ApprovalMatrixConfig", "approvalMatrixConfig")
                        .WithMany()
                        .HasForeignKey("approvalMatrixConfigId");

                    b.Navigation("approvalMatrixConfig");
                });

            modelBuilder.Entity("ASPER.CORPORATE_BANKING.Domain.Entities.ApprovalStep", b =>
                {
                    b.HasOne("ASPER.CORPORATE_BANKING.Domain.Entities.ApprovalMatrixSlab", "approvalMatrixSlab")
                        .WithMany()
                        .HasForeignKey("approvalMatrixSlabId");

                    b.Navigation("approvalMatrixSlab");
                });

            modelBuilder.Entity("ASPER.CORPORATE_BANKING.Domain.Entities.ApprovalStepRole", b =>
                {
                    b.HasOne("ASPER.CORPORATE_BANKING.Domain.Entities.ApprovalStep", "approvalStep")
                        .WithMany()
                        .HasForeignKey("approvalStepId");

                    b.Navigation("approvalStep");
                });

            modelBuilder.Entity("ASPER.CORPORATE_BANKING.Domain.Entities.FileFieldMapping", b =>
                {
                    b.HasOne("ASPER.CORPORATE_BANKING.Domain.Entities.FileTemplateConfig", "fileTemplateConfig")
                        .WithMany()
                        .HasForeignKey("fileTemplateConfigId");

                    b.Navigation("fileTemplateConfig");
                });

            modelBuilder.Entity("ASPER.CORPORATE_BANKING.Domain.Entities.FileTemplateConfig", b =>
                {
                    b.HasOne("ASPER.CORPORATE_BANKING.Domain.Entities.TransactionType", "transactionType")
                        .WithMany()
                        .HasForeignKey("transactionTypeId");

                    b.Navigation("transactionType");
                });

            modelBuilder.Entity("ASPER.CORPORATE_BANKING.Domain.Entities.TransactionApprovalAction", b =>
                {
                    b.HasOne("ASPER.CORPORATE_BANKING.Domain.Entities.TransactionRecord", "transactionRecord")
                        .WithMany()
                        .HasForeignKey("transactionRecordId");

                    b.Navigation("transactionRecord");
                });

            modelBuilder.Entity("ASPER.CORPORATE_BANKING.Domain.Entities.TransactionBatch", b =>
                {
                    b.HasOne("ASPER.CORPORATE_BANKING.Domain.Entities.ApprovalMatrixConfig", "approvalMatrixConfig")
                        .WithMany()
                        .HasForeignKey("approvalMatrixConfigId");

                    b.HasOne("ASPER.CORPORATE_BANKING.Domain.Entities.TransactionType", "transactionType")
                        .WithMany()
                        .HasForeignKey("transactionTypeId");

                    b.Navigation("approvalMatrixConfig");

                    b.Navigation("transactionType");
                });

            modelBuilder.Entity("ASPER.CORPORATE_BANKING.Domain.Entities.TransactionRecord", b =>
                {
                    b.HasOne("ASPER.CORPORATE_BANKING.Domain.Entities.ApprovalMatrixSlab", "matrixSlab")
                        .WithMany()
                        .HasForeignKey("matrixSlabId");

                    b.HasOne("ASPER.CORPORATE_BANKING.Domain.Entities.TransactionBatch", "transactionBatch")
                        .WithMany()
                        .HasForeignKey("transactionBatchId");

                    b.Navigation("matrixSlab");

                    b.Navigation("transactionBatch");
                });
#pragma warning restore 612, 618
        }
    }
}
